let dicionario = {
    "maçã": "fruta",
    "cachorro": "animal",
    "carro": "veículo"
};

console.log(dicionario["maçã"]); // Saída: fruta
console.log(dicionario["cachorro"]); // Saída: animal
console.log(dicionario["carro"]); // Saída: veículo

//Um dicionário em JavaScript é uma estrutura de dados que mapeia chaves para valores.
//. Em JavaScript, essa estrutura é comumente chamada de objeto. Um objeto JavaScript é uma coleção de pares.

let dicionario = {
    "chave1": "valor1",
    "chave2": "valor2",
    "chave3": "valor3"
};

// Acessando os valores do "dicionário"
console.log(dicionario["chave1"]); // Saída: valor1
console.log(dicionario["chave2"]); // Saída: valor2
console.log(dicionario["chave3"]); // Saída: valor3
//Neste exemplo, o objeto dicionario contém três pares chave-valor simples. As chaves ("chave1", "chave2,"chave3"